config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :username))
      ) &&
        ActiveSupport::SecurityUtils.secure_compare(
          ::Digest::SHA256.hexdigest(password),
          ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :password))
        )
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :offices, only: %i[index show] do
    get :suggest, on: :collection
    get :decrees, on: :member
  end

  resources :prosecutors, only: %i[index show] do
    get :suggest, on: :collection
    get :export, on: :collection
  end

  resources :statistics, only: :index, path: :'criminality/prosecutors' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  resources :crimes, only: :index, path: :'criminality/police' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  # error pages
  %w[400 404 422 500 503].each { |code| get "/#{code}", to: 'errors#show', code: code }

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/models/concerns/offices/indicators.rb
module Offices
  module Indicators
    extend ActiveSupport::Concern

    def convicted_people_by_years
      @convicted_people_by_years ||=
        statistics.where(metric: :convicted_all).where.not(paragraph: nil).group(:year).order(year: :asc).sum(:count)
    end

    def average_convicted_people_yearly
      @average_convicted_people_yearly ||=
        begin
          if convicted_people_by_years.blank?
            nil
          else
            convicted_people_by_years.values.sum / convicted_people_by_years.keys.size.to_f
          end
        end
    end

    def average_incoming_cases_per_prosecutor_monthly_by_years
      @average_incoming_cases_per_prosecutor_monthly_by_years ||=
        self.class.indicators[id].try { |e| e[:average_incoming_cases_per_prosecutor_monthly_by_years] }
    end

    def average_incoming_cases_per_prosecutor_monthly
      @average_incoming_cases_per_prosecutor_monthly ||=
        begin
          if average_incoming_cases_per_prosecutor_monthly_by_years.blank?
            nil
          else
            average_incoming_cases_per_prosecutor_monthly_by_years.values.sum /
              average_incoming_cases_per_prosecutor_monthly_by_years.keys.size.to_f
          end
        end
    end

    def average_incoming_cases_per_prosecutor_yearly_by_years
      @average_incoming_cases_per_prosecutor_yearly_by_years ||=
        self.class.indicators[id].try { |e| e[:average_incoming_cases_per_prosecutor_yearly_by_years] }
    end

    def average_incoming_cases_per_prosecutor_yearly
      @average_incoming_cases_per_prosecutor_yearly ||=
        if average_incoming_cases_per_prosecutor_yearly_by_years.blank?
          nil
        else
          average_incoming_cases_per_prosecutor_yearly_by_years.values.sum /
            average_incoming_cases_per_prosecutor_yearly_by_years.keys.size.to_f
        end
    end

    def average_filed_prosecutions_per_prosecutor_monthly_by_years
      @average_filed_prosecutoions_per_prosecutor_monthly_by_years ||=
        self.class.indicators[id].try { |e| e[:average_filed_prosecutions_per_prosecutor_monthly_by_years] }
    end

    def average_filed_prosecutions_per_prosecutor_monthly
      @average_filed_prosecutions_per_prosecutor_monthly ||=
        if average_filed_prosecutions_per_prosecutor_monthly_by_years.blank?
          nil
        else
          average_filed_prosecutions_per_prosecutor_monthly_by_years.values.sum /
            average_filed_prosecutions_per_prosecutor_monthly_by_years.keys.size.to_f
        end
    end

    def average_filed_prosecutions_per_prosecutor_yearly_by_years
      @average_filed_prosecutoions_per_prosecutor_yearly_by_years ||=
        self.class.indicators[id].try { |e| e[:average_filed_prosecutions_per_prosecutor_yearly_by_years] }
    end

    def average_filed_prosecutions_per_prosecutor_yearly
      @average_filed_prosecutions_per_prosecutor_yearly ||=
        if average_filed_prosecutions_per_prosecutor_yearly_by_years.blank?
          nil
        else
          average_filed_prosecutions_per_prosecutor_yearly_by_years.values.sum /
            average_filed_prosecutions_per_prosecutor_yearly_by_years.keys.size.to_f
        end
    end

    def prosecutors_count_by_years
      @prosecutors_count_by_years ||= self.class.indicators[id].try { |e| e[:prosecutors_count_by_years] }
    end

    def incoming_cases_by_years
      @incoming_cases_by_years ||= self.class.indicators[id].try { |e| e[:incoming_cases_by_years] }
    end

    def average_incoming_cases_yearly
      @average_incoming_cases_yearly ||=
        if incoming_cases_by_years.blank?
          nil
        else
          incoming_cases_by_years.values.sum / incoming_cases_by_years.keys.size.to_f
        end
    end

    def rest_cases_by_years
      @rest_cases_by_years ||= self.class.indicators[id].try { |e| e[:rest_cases_by_years] }
    end

    def average_rest_cases_yearly
      @rest_incoming_cases_yearly ||=
        rest_cases_by_years.blank? ? nil : rest_cases_by_years.values.sum / rest_cases_by_years.keys.size.to_f
    end

    def average_ratio_of_rest_to_incoming_cases_yearly
      @average_ratio_of_rest_to_incoming_cases_yearly ||= average_rest_cases_yearly / average_incoming_cases_yearly.to_f
    end

    def average_ratio_of_rest_to_incoming_cases_by_years
      @average_ratio_of_rest_to_incoming_cases_by_years ||=
        if rest_cases_by_years.blank?
          nil
        else
          rest_cases_by_years
            .each
            .with_object({}) { |(year, count), hash| hash[year] = count / incoming_cases_by_years[year].to_f }
        end
    end

    def to_indicators_chart_data
      years = [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019]
      key = ->(value) { "active_record.models.prosecutor.indicators.#{value}" }
      mapper =
        lambda do |data|
          break if data.blank?

          years.map { |year| data[year] }
        end

      data =
        [
          {
            id: :convicted,
            name: I18n.t(key.call('average_convicted_people.office')),
            data: mapper.call(convicted_people_by_years)
          },
          {
            name: I18n.t(key.call("average_convicted_people.#{type}")),
            data: mapper.call(self.class.average_convicted_people_by_years_by_office_type[type]),
            dependent: :convicted
          },
          {
            id: :incoming_cases_per_prosecutor,
            name: I18n.t(key.call('average_incoming_cases_per_prosecutor.office')),
            data: mapper.call(average_incoming_cases_per_prosecutor_yearly_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("average_incoming_cases_per_prosecutor.#{type}")),
            data: mapper.call(self.class.average_incoming_cases_per_prosecutor_by_years_by_office_type[type]),
            dependent: :incoming_cases_per_prosecutor
          },
          {
            id: :filed_prosecutions_per_prosecutor,
            name: I18n.t(key.call('average_filed_prosecutions_per_prosecutor.office')),
            data: mapper.call(average_filed_prosecutions_per_prosecutor_yearly_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("average_filed_prosecutions_per_prosecutor.#{type}")),
            data: mapper.call(self.class.average_filed_prosecutions_per_prosecutor_by_years_by_office_type[type]),
            dependent: :filed_prosecutions_per_prosecutor
          },
          {
            id: :prosecutors_count,
            name: I18n.t(key.call('prosecutors_count.office')),
            data: mapper.call(prosecutors_count_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("prosecutors_count.#{type}")),
            data: mapper.call(self.class.average_prosecutors_count_by_years_by_office_type[type]),
            dependent: :prosecutors_count
          },
          {
            id: :rest_cases,
            name: I18n.t(key.call('rest_cases.office')),
            data: mapper.call(rest_cases_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("rest_cases.#{type}")),
            data: mapper.call(self.class.average_rest_cases_by_years_by_office_type[type]),
            dependent: :rest_cases
          },
          {
            id: :incoming_cases,
            name: I18n.t(key.call('incoming_cases.office')),
            data: mapper.call(incoming_cases_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("incoming_cases.#{type}")),
            data: mapper.call(self.class.average_incoming_cases_by_years_by_office_type[type]),
            dependent: :incoming_cases
          },
          {
            id: :ratio_of_rest_to_incoming_cases,
            name: I18n.t(key.call('ratio_of_rest_to_incoming_cases.office')),
            data: mapper.call(average_ratio_of_rest_to_incoming_cases_by_years),
            visible: false
          },
          {
            name: I18n.t(key.call("ratio_of_rest_to_incoming_cases.#{type}")),
            data: mapper.call(self.class.average_ratio_of_rest_to_incoming_cases_by_years_by_office_type[type]),
            dependent: :ratio_of_rest_to_incoming_cases
          }
        ].select { |values| values[:data].present? }

      { years: years, data: data }
    end

    class_methods do
      def offices_map
        @offices_map ||=
          Office
            .all
            .each
            .with_object({}) do |office, acc|
              [office.id, office.name, *office.synonyms].compact.each { |name| acc[name] = office }
            end
      end

      def indicators
        @indicators ||= prepare_indicators
      end

      def average_convicted_people_yearly_by_office_type
        @average_convicted_people_yearly_by_office_type ||=
          compute_yearly_indicators_average_by_office_type(:average_convicted_people_yearly)
      end

      def average_convicted_people_by_years_by_office_type
        @average_convicted_people_by_years_by_office_type ||=
          compute_indicators_average_by_years_by_office_type(:convicted_people_by_years)
      end

      def average_incoming_cases_per_prosecutor_yearly_by_office_type
        @average_incoming_cases_per_prosecutor_yearly_by_office_type ||=
          compute_yearly_indicators_average_by_office_type(:average_incoming_cases_per_prosecutor_yearly)
      end

      def average_incoming_cases_per_prosecutor_by_years_by_office_type
        @average_incoming_cases_per_prosecutor_by_years_by_office_type ||=
          compute_indicators_average_by_years_by_office_type(:average_incoming_cases_per_prosecutor_yearly_by_years)
      end

      def average_filed_prosecutions_per_prosecutor_yearly_by_office_type
        @average_filed_prosecutions_per_prosecutor_yearly_by_office_type ||=
          compute_yearly_indicators_average_by_office_type(:average_filed_prosecutions_per_prosecutor_yearly)
      end

app/models/genpro_gov_sk/office.rb
# == Schema Information
#
# Table name: genpro_gov_sk_offices
#
#  id         :bigint           not null, primary key
#  data       :jsonb            not null
#  digest     :string           not null
#  file       :binary           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_genpro_gov_sk_offices_on_digest  (digest) UNIQUE
#
module GenproGovSk
  class Office < ApplicationRecord
    validates :data, presence: true
    validates :file, presence: true
    validates :digest, presence: true, uniqueness: true

    def self.import_from(data:, file:)
      digest = Digest::MD5.hexdigest(file)
      genpro_gov_sk_office = find_by(digest: digest)

      return if genpro_gov_sk_office && data.deep_stringify_keys == genpro_gov_sk_office.data.deep_stringify_keys

      genpro_gov_sk_office ||= new(digest: digest, file: file)

      ActiveRecord::Base.transaction do
        genpro_gov_sk_office.lock!
        genpro_gov_sk_office.update!(data: data)

        office = ::Office.find_or_initialize_by(name: data[:name])

        office.lock!
        office.update!(data.except(:employees).merge(genpro_gov_sk_office: genpro_gov_sk_office))

        office.employees.lock!

        employees =
          data[:employees].map do |params|
            employee = office.employees.active.find_or_initialize_by(params.slice(:name, :position))

            employee.update!(params)

            employee
          end

        office.employees.where.not(id: employees).update_all(disabled_at: Time.zone.now)
      end

      # TODO: Soft-destroy all offices that are not imported

      ::Office.refresh_search_view
    end
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  layout false, only: [:decrees]

  def index
    @search = OfficeSearch.new(index_params)

    @search.params[:sort] = nil if @search.params[:sort] == 'relevancy' && @search.params[:q].blank?
  end

  def show
    @office = Office.find(params[:id])
    @tab = show_params[:tab]
    @paragraphs = Paragraph.where(value: show_params[:paragraph]) if params[:paragraph].present?
    @decrees = @office.decrees
    @decrees = @decrees.where(paragraph: @paragraphs) if @paragraphs.present?
    @registry = @office.registry.deep_symbolize_keys
  end

  def suggest
    return head 404 unless suggest_params[:facet].in?(%w[city paragraph])

    @search = OfficeSearch.new(index_params)

    render(
      json: {
        html:
          render_to_string(
            partial: "#{suggest_params[:facet]}_results",
            locals: {
              values: @search.facets_for(suggest_params[:facet], suggest: suggest_params[:suggest]),
              params: @search.params
            }
          )
      }
    )
  end

  def decrees
    @office = Office.find(params[:id])
    @decrees = @office.decrees
    @paragraphs = Paragraph.where(value: decrees_params[:paragraph]) if decrees_params[:paragraph].present?
    @decrees = @decrees.where(paragraph: @paragraphs) if @paragraphs.present?
  end

  private

  helper_method :index_params, :show_params

  def index_params
    params.permit(:page, :sort, :order, :q, type: [], city: [], prosecutors_count: [], decrees_count: [], paragraph: [])
  end

  def show_params
    params.permit(:tab, paragraph: [])
  end

  def suggest_params
    params.permit(:facet, :suggest)
  end

  def decrees_params
    params.permit(paragraph: [])
  end
end

app/helpers/office_helper.rb
module OfficeHelper
  def offices_path(*args, &block)
    path = super(*args, &block)

    args.any? && args[0].any? ? "#{path}#facets" : path
  end

  def minified_office_name(name)
    return 'GP SR' if name == 'Generálna prokuratúra Slovenskej republiky'

    name.gsub('Krajská prokuratúra', 'KP').gsub('Okresná prokuratúra', 'OP')
  end
end

app/views/offices/_city_results.html.erb
<ul class="facet-list" data-target="suggest.results">
  <% if values.each do |city, count| %>
    <li class="facet-item">
      <%= link_to offices_path(search_params(params, { city: city })), class: "facet-link#{' active' if search_param?(params, :city, city)}" do %>
        <%= city %>
        <span class="facet-tag"><%= count %></span>
      <% end %>
    </li>
  <% end.empty? %>
    <li class="facet-item">
      <span class="text-muted"><%= t 'offices.index.search.city.not_found' %></span>
    </li>
  <% end %>
</ul>

app/views/offices/_decrees.html.erb
<%= render "decrees_table", loading: true do %>
  <% [@decrees.count, 100].min.times do %>
    <tr class="p-2">
      <td colspan="7">
        <div class="bg-loading" style="height: 25px">
        </div>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/offices/decrees.html.erb
<%= render "decrees_table", loading: false do %>
  <% @decrees.includes(:prosecutor, :paragraph).order(effective_on: :asc).each do |decree| %>
    <tr>
      <td data-search-value="<%= decree.prosecutor&.name %>"><%= decree.prosecutor ? link_to(decree.prosecutor.name, prosecutor_path(decree.prosecutor), target: :_top) : '&ndash;'.html_safe %></td>
      <td><%= link_to decree.number, decree.url, target: :_blank %></td>
      <td data-value="<%= decree.effective_on %>"><%= tooltip_tag(l(decree.effective_on), t('.published', date: l(decree.published_on))) %></td>
      <td><%= decree.file_number %></td>
      <td data-search-value="<%= decree.paragraph&.name %>">
        <%=
          decree.paragraph ? tooltip_tag(
            decree.paragraph.name,
            decree.paragraph.type_old? ? [I18n.t("statistics.index.search.paragraph.old.title"), decree.paragraph_section].join(' &ndash; '.html_safe) : decree.paragraph_section
          ) : '&ndash;'.html_safe
        %>
      </td>
      <td data-search-value="<%= decree.resolution %>"><%= decree.resolution %></td>
      <td data-search-value="<%= decree.means_of_resolution %>"><%= decree.means_of_resolution %></td>
    </tr>
  <% end %>
<% end %>

app/views/offices/index.html.erb
<% provide :title, t('.title') %>

<div class="container mt-4 px-sm-0">
  <div class="clearfix">
    <div class="float-lg-right col-lg-12 mb-3 mb-lg-4 px-0">
      <div class="row align-items-center justify-content-between">
        <h1 class="col col-xl-4 display-2 text-uppercase mr-sm-4 mt-1 pr-5">
          <%= t '.title' %>
        </h1>

        <div class="col-lg-6 col-xl">
          <%= form_tag offices_path, method: :get, class: 'search-query-form mb-0' do %>
            <div class="input-group">
              <%= search_field_tag :q, @search.params[:q], class: 'form-control search-query-input', placeholder: t('.search.placeholder') %>
              <div class="input-group-append">
                <%= link_to icon_tag('times'), offices_path(@search.params.except(:q, :sort, :order)), class: 'btn search-query-reset mt-1' if @search.params[:q].present? %>
                 <% unless @search.params[:q].present? %>
                  <button type="submit" class="btn mt-1 search-query-submit"><%= icon_tag('search') %></button>
                <% end %>
              </div>
            </div>

            <% form_params @search.params.except(:q, :page) do |name, value| %>
              <%= hidden_field_tag name, value %>
            <% end %>
            <%= hidden_field_tag :l, I18n.locale %>
            <%= hidden_field_tag :sort, :relevancy if params[:sort].blank? %>
            <%= hidden_field_tag :order, :desc if params[:order].blank? %>
          <% end %>
        </div>
      </div>
    </div>

    <div id="map" class="w-100 mb-4 mb-lg-4" data-controller="map" data-json="<%= @search.all.as_map_json.to_json %>"></div>

    <div id="facets" class="float-lg-left col-lg-3 mb-5 mb-lg-0 px-0 pr-lg-4">
      <div class="facet no-border" data-id="office-sort">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-sort-content">
          <%= t '.search.sort.title' %>
        </h6>

        <div id="office-sort-content" class="facet-content collapse show">
          <div class="btn-toolbar w-100" role="toolbar">
            <div class="btn-group btn-group-sm border mb-3 d-flex w-100" role="group">
              <div class="btn-group btn-group-sm flex-grow-1 d-flex" role="group">
                <button type="button" class="btn btn-secondary dropdown-toggle shadow-none border-left-0 border-right border-top-0 border-bottom-0 flex-grow-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%=  t ".search.sort.#{@search.params[:sort] || :default}" %>
                </button>
                <div class="dropdown-menu dropdown-menu-sm">
                  <%= link_to t('.search.sort.default'), offices_path(@search.params.merge(sort: nil)), class: 'dropdown-item' %>
                  <%= link_to t('.search.sort.name'), offices_path(@search.params.merge(sort: :name)), class: 'dropdown-item' %>
                  <%= link_to t('.search.sort.type'), offices_path(@search.params.merge(sort: :type)), class: 'dropdown-item' %>
                  <% if @search.params[:q] %>
                    <%= link_to t('.search.sort.relevancy'), offices_path(@search.params.merge(sort: :relevancy)), class: 'dropdown-item' %>
                  <% end %>
                </div>
              </div>
              <%= link_to icon_tag('arrow-up', size: 12), offices_path(@search.params.merge(order: 'asc')), class: "btn btn-secondary#{' active' if @search.params[:order] == 'asc'} d-flex align-items-center shadow-none border-left border-right border-top-0 border-bottom-0" %>
              <%= link_to icon_tag('arrow-down', size: 12), offices_path(@search.params.merge(order: 'desc')), class: "btn btn-secondary#{' active' if @search.params[:order] == 'desc'} d-flex align-items-center shadow-none border-left border-right-0 border-top-0 border-bottom-0" %>
            </div>
          </div>

          <% if @search.params.any? { |_, v| v.present? } %>
            <div class="btn-group btn-group-sm border mr-2 mb-3 d-flex w-100" role="group">
              <%= link_to t('layouts.search.reset'), offices_path, class: 'btn btn-secondary btn-sm shadow-none border-0 w-100' %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-type-content">
          <%= t '.search.type.title' %>
        </h6>

        <div id="office-type-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <% if @search.facets_for(:type).each do |key, count| %>
                <li class="facet-item">
                  <%= link_to offices_path(search_params(@search.params, { type: key })), class: "facet-link#{' active' if search_param?(@search.params, :type, key)}" do %>
                    <%= t("offices.types.#{key}") %>
                    <span class="facet-tag"><%= number_with_delimiter(count) %></span>
                  <% end %>
                </li>
              <% end.empty? %>
                <li class="facet-item">
                  <span class="text-muted"><%= t '.search.type.not_found' %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="facet" data-controller="suggest" data-url="<%= suggest_offices_path(@search.params.merge(facet: :city)) %>">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-city-content">
          <%= t '.search.city.title' %>
        </h6>

        <div id="office-city-content" class="facet-content collapse show">
          <div class="facet-results">
            <input class="facet-suggest ui-autocomplete-input" name="city" data-target="suggest.query" data-action="keyup->suggest#onChange" placeholder="<%= t '.search.city.placeholder' %>" type="text" autocomplete="off">
            <%= render 'city_results', values: @search.facets_for(:city, selected_first: true), params: @search.params %>
          </div>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-prosecutors-count-content">
          <%= t '.search.prosecutors_count.title' %>
        </h6>

        <div id="office-prosecutors-count-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <% if @search.facets_for(:prosecutors_count).each do |key, count| %>
                <li class="facet-item">
                  <%= link_to offices_path(search_params(@search.params, { prosecutors_count: key })), class: "facet-link#{' active' if search_param?(@search.params, :prosecutors_count, key)}" do %>

                    <%= range_with_count(key, term_for_count: 'terms.prosecutors') %>
                    <span class="facet-tag"><%= number_with_delimiter(count) %></span>
                  <% end %>
                </li>
              <% end.empty? %>
                <li class="facet-item">
                  <span class="text-muted"><%= t '.search.prosecutors_count.not_found' %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-decrees-count-content">
          <%= t '.search.decrees_count.title' %>
        </h6>

        <div id="office-decrees-count-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <% if @search.facets_for(:decrees_count).each do |key, count| %>
                <li class="facet-item">
                  <%= link_to offices_path(search_params(@search.params, { decrees_count: key })), class: "facet-link#{' active' if search_param?(@search.params, :decrees_count, key)}" do %>

                    <%= range_with_count(key, term_for_count: 'terms.decrees') %>
                    <span class="facet-tag"><%= number_with_delimiter(count) %></span>
                  <% end %>
                </li>
              <% end.empty? %>
                <li class="facet-item">
                  <span class="text-muted"><%= t '.search.decrees_count.not_found' %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="facet" data-controller="suggest" data-url="<%= suggest_offices_path(@search.params.merge(facet: :paragraph)) %>">
        <h6 class="facet-title" data-toggle="collapse" data-target="#office-paragraph-content">
          <%= t ".search.paragraph.title" %>
        </h6>

        <div id="office-paragraph-content" class="facet-content collapse show">
          <div class="facet-results">
            <input class="facet-suggest ui-autocomplete-input" name="paragraph" data-target="suggest.query" data-action="keyup->suggest#onChange" placeholder="<%= t '.search.paragraph.placeholder' %>" type="text" autocomplete="off">

            <%= render "paragraph_results", values: @search.facets_for(:paragraph, selected_first: true), params: @search.params %>

            <small class="text-muted mt-2"><%= t '.search.paragraph.disclaimer' %></small>
          </div>
        </div>
      </div>
    </div>

    <% time = Benchmark.realtime do %>
      <div class="float-lg-right col-lg-9 px-0">
        <ol class="search-result-list" start="1">
          <% if @search.paginated.each do |office| %>
            <li class="search-result-item">
              <h4 class="search-result-title">
                <%= link_to office.name, office_path(office, tab: index_params[:paragraph].present? ? 'decrees' : nil, paragraph: index_params[:paragraph]) %>
                <small>
                  <%= office.full_address %>
                </small>
              </h4>

              <div class="search-result-content">
                <% if office.specialized? %>
                  <div class="alert alert-danger mb-2">
                    <%= t '.specialized_office_info' %>
                  </div>
                <% end %>

                <% if office.attorney_general&.prosecutor  %>
                  <%= t ".list.prosecutor_subtitle.#{office.type}_html", link: link_to(office.attorney_general.prosecutor.name, prosecutor_path(office.attorney_general.prosecutor)) %>
                   <br>
                <% end %> 

                <%= t '.register' %>
                <%=
                  [
                    t('.prosecutors_count', count: office.prosecutors.count),
                    t('.employees_count', count: office.employees.active.count),
                    office.decrees_count.positive? ? t('terms.decrees_with_count', count: office.decrees_count) : nil,
                    office.articles.any? ? t('terms.news', count: office.articles.count) : nil
                  ].compact.to_sentence
                %>.
              </div>
            </li>
          <% end.empty? %>
            <div class="alert alert-info mb-0" role="alert">
              <%= t '.search.no_results' %>
            </div>
          <% end %>
        </ol>
      <% end * 1000 %>

      <div class="d-flex flex-wrap align-items-center justify-content-between">
        <div class="small text-muted mr-3 mt-4">
          <% if @search.all.any? %>
            <%= t 'layouts.search.found_with_timing_html', count: "#{@search.paginated.offset_value + 1} &ndash; #{@search.paginated.offset_value + @search.paginated.count}".html_safe, total: I18n.t('offices.count', count: @search.paginated.total_count), time: time.to_i %>
          <% else %>
            <%= t '.search.not_found', time: number_with_delimiter(time.to_i) %>
          <% end %>
        </div>

        <% if @search.paginated.any? %>
          <nav class="d-flex align-items-center justify-content-end mt-4">
            <%= paginate @search.paginated %>
          </nav>
        <% end %>
      </div>
    </div>
  </div>
</div>