config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :username))
      ) &&
        ActiveSupport::SecurityUtils.secure_compare(
          ::Digest::SHA256.hexdigest(password),
          ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :password))
        )
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :offices, only: %i[index show] do
    get :suggest, on: :collection
    get :decrees, on: :member
  end

  resources :prosecutors, only: %i[index show] do
    get :suggest, on: :collection
    get :export, on: :collection
  end

  resources :statistics, only: :index, path: :'criminality/prosecutors' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  resources :crimes, only: :index, path: :'criminality/police' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  # error pages
  %w[400 404 422 500 503].each { |code| get "/#{code}", to: 'errors#show', code: code }

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/models/statistic.rb
# == Schema Information
#
# Table name: statistics
#
#  id         :bigint           not null, primary key
#  count      :integer          not null
#  metric     :string           not null
#  paragraph  :string
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  office_id  :bigint           not null
#
# Indexes
#
#  index_statistics_on_metric                                       (metric)
#  index_statistics_on_office_id                                    (office_id)
#  index_statistics_on_paragraph                                    (paragraph)
#  index_statistics_on_paragraph_and_metric                         (paragraph,metric)
#  index_statistics_on_present_paragraph                            (paragraph) WHERE (paragraph IS NOT NULL)
#  index_statistics_on_year                                         (year)
#  index_statistics_on_year_and_office_id_and_metric_and_paragraph  (year,office_id,metric,paragraph) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (office_id => offices.id)
#

class Statistic < ApplicationRecord
  belongs_to :office

  validates :year, presence: true, numericality: { in: 2010..2020 }
  validates :metric,
            presence: true,
            uniqueness: {
              scope: %i[year office_id paragraph]
            },
            inclusion: {
              in: -> { GROUPS.values.flatten }
            }
  validates :count, presence: true, numericality: true

  def self.import_from(records)
    Statistic.transaction do
      Statistic.delete_all
      Statistic.lock

      offices = Office.all_by_name_map

      records.each { |record| record[:office_id] = offices[record[:office]] }

      Rails.logger.silence do
        records.each do |record|
          Statistic.upsert(
            { paragraph: nil }.merge(record.slice(:year, :office_id, :metric, :paragraph, :count)),
            unique_by: %i[year office_id metric paragraph],
            returning: false
          )
        end
      end

      nil
    end
  end

  GROUPS = {
    accused: %i[
      accused_all
      accused_men
      accused_women
      accused_age_14_to_15_all
      accused_age_14_to_15_boys
      accused_age_14_to_15_girls
      accused_age_16_to_18_all
      accused_age_16_to_18_boys
      accused_age_16_to_18_girls
      accused_age_19_to_21_all
      accused_age_22_to_30_all
      accused_age_31_to_40_all
      accused_age_41_to_50_all
      accused_age_51_to_60_all
      accused_age_61_and_more_all
      accused_recidivists_all
      accused_recidivists_dangerous
      accused_recidivists_only
      accused_alcohol_abuse
      accused_substance_abuse
      accused_by_paragraph_204
      accused_people_for_intentional_crimes
      accused_people_for_intentional_crimes_of_same_nature
    ],
    prosecuted: %i[
      prosecuted_all
      prosecuted_men
      prosecuted_women
      prosecuted_young
      prosecuted_foreigners
      prosecuted_alcohol_abuse
      prosecuted_substance_abuse
    ],
    convicted: %i[convicted_all convicted_men convicted_women convicted_young],
    closure: %i[
      _closure_all
      assignation_of_prosecution
      guilt_and_sentence_agreement
      reconciliation_approval
      suspension_of_prosecution
      suspension_of_prosecution_of_cooperating_accused
      cessation_of_prosecution
      conditional_cessation_by_court
      conditional_cessation_by_prosecutor
      conditional_cessation_by_prosecutor_all
      conditional_cessation_of_accused_all
      conditional_cessation_of_accused_and_proven
      conditional_cessation_of_accused_and_proven_by_prosecutor
      conditional_cessation_of_accused_by_prosecutor
      conditional_cessation_of_cooperating_accused_and_proven
      conditional_cessation_of_cooperating_accused_by_prosecutor
      valid_court_decision_all
      valid_court_decision_on_assignation_of_prosecution
      valid_court_decision_on_cessation_of_prosecution
      valid_court_decision_on_conditional_cessation_of_prosecution
      valid_court_decision_on_conditional_cessation_of_prosecution_of_cooperating_accused
      valid_court_decision_on_conviction_of_people
      valid_court_decision_on_exemption
      valid_court_decision_on_reconciliation_approval
      valid_court_decision_on_suspension_of_prosecution
      valid_court_decision_on_waiver_of_sentence
      valid_court_decision_only_convicted_with_guilt_and_sentence_agreement
      valid_other_court_decision
    ],
    prosecution_by_police: %i[
      prosecution_of_unknown_offender_ended_by_police
      prosecution_of_unknown_offender_ended_by_police_by_assignation
      prosecution_of_unknown_offender_ended_by_police_by_cessation
      prosecution_of_unknown_offender_ended_by_police_by_suspension
      prosecution_of_unknown_offender_ended_by_police_by_other_mean
    ],
    sentence: %i[
      _sentence_all
      sentence_by_os_47_2_tz
      sentence_financial
      sentence_nepo
      sentence_of_compulsary_labor
      sentence_of_forfeiture_of_possesion
      sentence_of_forfeiture_of_property
      sentence_other
      sentence_po
      sentence_prohibition_of_movement
      sentence_prohibition_of_practice
      sentence_prohibition_of_stay
      sentence_under_home_arrest
      sentence_waived
      sentence_of_deportation
    ],
    other: %i[judged_all closed_cases incoming_cases exemption protective_measures_imposed]
  }.freeze
end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
  def index
    @search = StatisticSearch.new(index_params)
    @time = Benchmark.realtime { @data = @search.data } * 1000
    @count = Rails.cache.fetch('statistics_count', expires_in: 1.day) { Statistic.count }
  end

  def suggest
    return head 404 unless suggest_params[:facet].in?(%w[office paragraph])

    @search = StatisticSearch.new(index_params)

    render(
      json: {
        html:
          render_to_string(
            partial: "#{suggest_params[:facet]}_results",
            locals: {
              values: @search.facets_for(suggest_params[:facet], suggest: suggest_params[:suggest]),
              params: @search.params.merge("#{suggest_params[:facet]}_suggest" => suggest_params[:suggest])
            }
          )
      }
    )
  end

  def png
    path = Rails.root.join('tmp', "statistics-export-#{SecureRandom.hex}.png")
    url = export_statistics_url(index_params)

    options = Selenium::WebDriver::Chrome::Options.new(args: %w[headless])
    options.add_argument('--window-size=1400,760')
    options.add_argument('--enable-font-antialiasing')
    options.add_argument('--force-device-scale-factor=2')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-extensions')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-setuid-sandbox')
    options.add_option(:detach, false)
    driver = Selenium::WebDriver.for(:chrome, options: options)

    begin
      driver.get(url)
      driver.manage.window.resize_to(1400, driver.execute_script('return document.body.scrollHeight') + 25)
      driver.save_screenshot(path)

      File.open(path, 'rb') do |file|
        send_data(file.read, type: 'image/png', filename: 'otvorena-prokuratura-kriminalita-export.png')
      end
    rescue Exception => e
      raise e
    ensure
      driver.quit
      File.delete(path)
    end
  end

  def export
    response.headers['X-FRAME-OPTIONS'] = 'ALLOWALL'

    index

    render layout: 'export'
  end

  def embed
    index
  end

  private

  helper_method :index_params

  def index_params
    params.permit(
      :comparison,
      :paragraph_suggest,
      :show_default_paragraphs,
      year: [],
      office: [],
      metric: [],
      office_type: [],
      paragraph: []
    )
  end

  def suggest_params
    params.permit(:facet, :suggest)
  end
end

app/helpers/statistics_helper.rb
module StatisticsHelper
  def statistics_subtitle(search)
    metric = search.current_statistic_metric
    paragraphs = search.current_statistic_paragraphs
    group = Statistic::GROUPS.find { |group, values| metric.to_sym.in?(values) }[0]
    key = search.default_params? ? 'statistics.index.subtitle_for_default_params' : 'statistics.index.subtitle'

    unless search.default_params?
      translation = I18n.t("statistics.index.search.#{group}.metrics.#{metric}", default: nil)

      unless translation
        translation = I18n.t("models.statistic.metrics.#{metric}")
        translation = "#{I18n.t("statistics.index.search.#{group}.title")} – #{translation}" unless group == :other
      end
    end

    paragraphs -= %w[_all] if paragraphs

    return I18n.t(key, metric: translation) if paragraphs&.compact.blank?

    paragraph_names = paragraphs.map { |value| Paragraph.by_value[value] }

    paragraphs_list =
      content_tag :div, class: 'mt-3' do
        content_tag :small do
          content_tag :ul, class: 'list-unstyled ml-3 paragraphs-list' do
            paragraph_names.map do |name|
              content_tag(:li, class: 'mt-1 d-flex') do
                (
                  content_tag(:span, name, class: 'text-truncate') +
                    (
                      if Paragraph.type_of(Paragraph.by_name[name]) == :old
                        content_tag(:span, class: 'ml-2 facet-tag') do
                          tooltip_tag(
                            I18n.t('statistics.index.search.paragraph.old.badge'),
                            I18n.t('statistics.index.search.paragraph.old.title')
                          )
                        end
                      else
                        ''
                      end
                    ) +
                    link_to(
                      '&times;'.html_safe,
                      statistics_path(
                        search_params(
                          @search.params.merge(paragraph: paragraphs),
                          { paragraph: Paragraph.by_name[name] }
                        )
                      ),
                      class: 'flex-fill ml-2 cancel'
                    )
                ).html_safe
              end
            end.join.html_safe
          end
        end
      end

    I18n.t("#{key}_with_paragraphs", metric: translation, paragraphs: paragraphs_list).html_safe
  end
end

app/views/statistics/_export.html.erb
<div class="statistics-export">
  <div class="d-flex flex-wrap align-items-center justify-content-between">
  <h1 class="display-2 text-uppercase mr-sm-4 mt-1 pr-5">
    <%= t 'statistics.index.title' %>
  </h1>

  <%= brand_tag('transparency-international-slovensko', width: 197.92, height: 47.5, variant: I18n.locale) %>

  <div class="w-100" data-controller="chart" data-json="<%= @data.to_json %>" data-selected-offices="<%= (@search.params.values_at(:office, :office_type).flatten.compact.blank? ? [@search.office_aggregate_key] : @search.data[:data].select { |e| e[:office] }.map { |e| e[:name] }.uniq).to_json %>" data-animation="false">
    <h1 class="text-uppercase">
      <small class="text-muted">
        <% if @search.default_params? %>
          <%= t('statistics.index.subtitle_for_default_params') %>
        <% else %>
          <%= statistics_subtitle(@search.current_statistic_metric, @search.current_statistic_paragraphs) %>
        <% end %>
      </small>
    </h1>

    <% if @search.data[:data].select { |e| e[:office] }.any? %>
      <div class="mt-5 chart"></div>

      <small class="mt-2 text-muted float-right">
        <%= t 'statistics.index.data_source_disclaimer' %>
      </small>
    <% else %>
      <p class="text-center text-muted mt-5 p-5"><%= t '.no_data' %></p>
    <% end %>
</div>
</div>

app/views/statistics/_office_results.html.erb
<ul class="facet-list" data-target="suggest.results">
  <% if values.each do |name, _| %>
    <li class="facet-item">
      <%= link_to statistics_path(search_params(params, { office: name })), class: "facet-link#{' active' if search_param?(params, :office, name)}" do %>
        <%= trim(minified_office_name(name)) %>
      <% end %>
    </li>
  <% end.empty? %>
    <li class="facet-item">
      <span class="text-muted"><%= t 'statistics.index.search.office.not_found' %></span>
    </li>
  <% end %>
</ul>

app/views/statistics/_paragraph_results.html.erb
<ul class="facet-list facet-list-scrollable mb-2" data-target="suggest.results">
  <% if values.any? %>
    <% values.each do |value, _| %>
      <li class="facet-item">
        <%= link_to statistics_path(search_params(params, { paragraph: value })), class: "facet-link#{' active' if search_param?(params, :paragraph, value)}" do %>
          <%= trim(Paragraph.name_of(value), length: 24) %>

          <div class="facet-tag">
            <% if (type = Paragraph.type_of(value)) == :old %>
              <%= tooltip_tag(I18n.t("statistics.index.search.paragraph.old.badge"),  I18n.t("statistics.index.search.paragraph.old.title"), class: 'd-inline') %>
            <% end %>
          </div>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li class="facet-item">
      <span class="text-muted"><%= t 'statistics.index.search.paragraph.not_found' %></span>
    </li>
  <% end %>
</ul>

app/views/statistics/embed.html.erb
<iframe src="<%= export_statistics_url(@search.params.merge(embedded: true)) %>" width="100%" height="<%= params[:show_default_paragraphs].present? ? 1280 : 800 %>px" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups">
  <p>
    <a href="https://developer.mozilla.org/en-US/docs/Glossary">Fallback link for browsers that don't support iframes</a>
  </p>
</iframe>

<div class="form-group">
  <textarea name="embed" id="embed" rows="10" cols="40" class="w-100 mt-3 form-control" disabled="true">
    <iframe src="<%= export_statistics_url(@search.params.merge(embedded: true)) %>" width="100%" height="<%= params[:show_default_paragraphs].present? ? 1280 : 800 %>px" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups">
      <p>
        <a href="https://developer.mozilla.org/en-US/docs/Glossary">Fallback link for browsers that don't support iframes</a>
      </p>
    </iframe>
  </textarea>
</div>

app/views/statistics/export.html.erb
<div class="statistics-export">
  <div class="d-flex flex-wrap align-items-center justify-content-between">
  <h1 class="display-2 text-uppercase mr-sm-4 mt-1 pr-5">
    <%= t 'statistics.index.title' %>
  </h1>

  <%= brand_tag('transparency-international-slovensko', width: 197.92, height: 47.5, variant: I18n.locale) %>

  <div
    class="w-100"
    data-controller="statistics-chart"
    data-json="<%= @data.to_json %>"
    data-comparison="<%= @search.comparison %>"
    data-animation="false"
  >
    <h1 class="text-uppercase">
      <small class="text-muted">
        <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
          <%= t 'statistics.index.subtitle_for_default_params' %>
        <% else %>
          <%= statistics_subtitle(@search) %>
        <% end %>
      </small>
    </h1>

    <% if @search.data[:data].select { |e| e[:office] }.any? %>
      <div class="mt-5 chart"></div>

      <small class="mt-2 text-muted float-right text-right">
        <%= t 'statistics.index.data_disclaimer' %>
        <br>
        <% if params[:embedded] %>
          <%= link_to t('.open_in_application'), statistics_url(@search.params), class: 'text-muted', target: :_blank %>
          &middot;&nbsp;
        <% end %>
        <%= t 'statistics.index.data_source_disclaimer_html' %>
      </small>
    <% else %>
      <p class="text-center text-muted mt-5 p-5"><%= t '.no_data' %></p>
    <% end %>
  </div>
</div>

app/views/statistics/index.html.erb
<% provide :title, t('.page_title') %>

<%
  @time = Benchmark.realtime do
    @data = @search.data
  end * 1000
%>

<div class="container px-sm-0" data-controller="facets">
  <div class="clearfix">
    <div id="facets" class="float-lg-left col-lg-3 mb-5 mb-lg-0 px-0 pr-lg-4 collapse show">
      <div class="facet" data-controller="suggest" data-url="<%= suggest_statistics_path(@search.params.merge(facet: :paragraph)) %>">
        <h6 class="facet-title" data-toggle="collapse" data-target="#statistic-paragraph-content">
          <%= t ".search.paragraph.title" %>
        </h6>

        <div id="statistic-paragraph-content" class="facet-content collapse show">
          <div class="facet-results">
            <input value="<%= params[:paragraph_suggest] %>" class="facet-suggest ui-autocomplete-input" name="paragraph" data-target="suggest.query" data-action="keyup->suggest#onChange" placeholder="<%= t '.search.paragraph.placeholder' %>" type="text" autocomplete="off">

            <% if (facets = @search.facets_for(:paragraph, selected_first: true)).any? %>
              <ul class="facet-list">
                <li class="facet-item">
                  <%= link_to statistics_path(search_params(@search.params, { paragraph: '_all', paragraph_suggest: nil, }, replace: true)), class: "facet-link#{' active' if @search.params[:paragraph].blank? && !@search.default_params?}" do %>
                    <%= t('.search.paragraphs.all') %>
                  <% end %>
                </li>
              </ul>
            <% end %>

            <%= render "paragraph_results", values: facets, params: @search.params %>

            <small class="text-muted mt-2"><%= t '.search.paragraph.disclaimer' %></small>
          </div>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#statistic-year-content">
          <%= t '.search.year.title' %>
        </h6>

        <div id="statistic-year-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <li class="facet-item">
                <%= link_to statistics_path(search_params(@search.params, { year: nil })), class: "facet-link#{' active' if @search.params[:year].blank?}" do %>
                  <%= t('.search.year.all') %>
                <% end %>
              </li>
            </ul>

            <% if @search.facets_for(:year).tap do |facets| %>
              <%= collapsible_facet_results(facets, selected: @search.params[:year]) do |key, _| %>
                <li class="facet-item">
                  <%= link_to statistics_path(search_params(@search.params, { year: key })), class: "facet-link#{' active' if search_param?(@search.params, :year, key)}" do %>
                    <%= key %>
                  <% end %>
                </li>
              <% end %>
            <% end.empty? %>
              <span class="text-muted"><%= t '.search.year.not_found' %></span>
            <% end %>
          </div>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#statistic-office-type-content">
          <%= t '.search.office_type.title' %>
        </h6>

        <div id="statistic-office-type-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <% if @search.facets_for(:office_type).each do |key, _| %>
                <li class="facet-item">
                  <%= link_to statistics_path(search_params(@search.params, { office_type: key })), class: "facet-link#{' active' if search_param?(@search.params, :office_type, key)}" do %>
                    <%= t("offices.types.#{key}") %>
                  <% end %>
                </li>
              <% end.empty? %>
                <li class="facet-item">
                  <span class="text-muted"><%= t '.search.office_type.not_found' %></span>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

      <div class="facet" data-controller="suggest" data-url="<%= suggest_statistics_path(@search.params.merge(facet: :office)) %>">
        <h6 class="facet-title" data-toggle="collapse" data-target="#statistic-office-content">
          <%= t '.search.office.title' %>
        </h6>

        <div id="statistic-office-content" class="facet-content collapse show">
          <div class="facet-results">
            <input class="facet-suggest ui-autocomplete-input" name="office" data-target="suggest.query" data-action="keyup->suggest#onChange" placeholder="<%= t '.search.office.placeholder' %>" type="text" autocomplete="off">
            <ul class="facet-list">
              <li class="facet-item">
                <%= link_to statistics_path(search_params(@search.params, { office: nil })), class: "facet-link#{' active' if @search.params[:office].blank?}" do %>
                  <%= t('.search.office.all') %>
                <% end %>
              </li>

              <li class="facet-item">
                <%= link_to statistics_path(search_params(@search.params, { office: '_all' }, replace: true)), class: "facet-link#{' active' if @search.params[:office] == ['_all']}" do %>
                  <%= t('.search.office.by_all') %>
                <% end %>
              </li>
            </ul>

            <%= render 'office_results', values: @search.facets_for(:office, selected_first: true), params: @search.params %>
          </div>
        </div>
      </div>

      <% Statistic::GROUPS.each do |group, metrics| %>
        <% metrics.select { |metric| @search.has_metric?(metric) }.tap do |facets| %>
          <% if facets.any? %>
            <div class="facet">
              <h6 class="facet-title" data-toggle="collapse" data-target="#statistic-<%= group %>-content">
                <%= t ".search.#{group}.title" %>
              </h6>

              <div id="statistic-<%= group %>-content" class="facet-content collapse show">
                <div class="facet-results">
                  <%= collapsible_facet_results(facets, selected: @search.params[:metric]) do |key| %>
                    <li class="facet-item">
                      <%= link_to statistics_path(search_params(@search.params, { metric: key }, replace: true)), class: "facet-link#{' active' if search_param?(@search.params, :metric, key)}" do %>
                        <%= trim(t("models.statistic.metrics.#{key}"), length: 30) %>
                      <% end %>
                    </li>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="float-lg-right col-lg-9 px-0" data-results-for-facets>
      <div class="d-flex flex-wrap align-items-center justify-content-between">
        <h1 class="display-2 text-uppercase mr-sm-4 mt-1 pr-5">
          <%= t '.title' %>
        </h1>

        <div class="btn-toolbar" role="toolbar">
          <% if @search.params.any? { |_, v| v.present? } %>
            <div class="btn-group btn-group-sm border mb-3 mr-2" role="group">
              <%= link_to t('layouts.search.reset'), statistics_path, class: 'btn btn-secondary btn-sm shadow-none border-0 w-100', 'data-turbo': false %>
            </div>
          <% end %>

          <div class="btn-group btn-group-sm border mb-3" role="group">
            <a href="#" class="btn btn-secondary btn-sm shadow-none border-0 w-100" data-toggle="collapse" data-target="#facets" aria-controls="#facets" aria-expanded="true">
              <span class="show"><%= t '.shrink_chart' %></span>
              <span class="hide"><%= t '.enlarge_chart' %></span>
            </a>
          </div>

          <div class="btn-group btn-group-sm border mb-3 ml-2">
            <div class="btn-group btn-group-sm flex-grow-1 d-flex" role="group">
              <button type="button" class="btn btn-secondary dropdown-toggle shadow-none border-0 flex-grow-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%=  t ".comparison.title" %>
              </button>
              <div class="dropdown-menu dropdown-menu-sm">
                <%= link_to t('.comparison.global'), statistics_path(@search.params.merge(comparison: nil)), class: "dropdown-item #{'active' if @search.comparison == 'global'}" %>
                <%= link_to t('.comparison.office'), statistics_path(@search.params.merge(comparison: 'office')), class: "dropdown-item #{'active' if @search.comparison == 'office'}" %>
                <% if @search.paragraphs_present? %>
                  <%= link_to t('.comparison.paragraph'), statistics_path(@search.params.merge(comparison: 'paragraph')), class: "dropdown-item #{'active' if @search.comparison == 'paragraph'}" %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="btn-group btn-group-sm border mb-3 ml-2">
            <div class="btn-group btn-group-sm flex-grow-1 d-flex" role="group">
              <button type="button" class="btn btn-secondary dropdown-toggle shadow-none border-0 flex-grow-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%=  t 'Export' %>
              </button>
              <div class="dropdown-menu dropdown-menu-sm">
                <%= link_to 'PNG', png_statistics_path(index_params), class: 'dropdown-item', target: :_blank %>
                <%= link_to 'Embed', embed_statistics_path(index_params), class: 'dropdown-item', target: :_blank %>
              </div>
            </div>
          </div>
        </div>

        <div
          class="w-100"
          data-controller="statistics-chart"
          data-watermark-url="<%= image_url("brands/transparency-international-slovensko.#{I18n.locale}.svg") %>"
          data-comparison="<%= @search.comparison %>"
          data-json="<%= @data.to_json %>"
        >
          <h1 class="text-uppercase">
            <small class="text-muted">
              <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
                <%= t '.subtitle_for_default_params' %>
              <% else %>
                <%= statistics_subtitle(@search) %>
              <% end %>
            </small>
          </h1>

          <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
            <%= link_to t('.show_paragraphs'), statistics_path(@search.params.merge(show_default_paragraphs: true)), class: 'text-muted' %>
          <% end %>

          <% if @search.data[:data].reject { |e| e[:global] }.any? %>
            <div class="mt-5 chart"></div>

            <small class="mt-2 text-muted float-right text-right">
              <%= t '.data_disclaimer' %>
            </small>
          <% else %>
            <p class="text-center text-muted mt-5 p-5"><%= t '.no_data' %></p>
          <% end %>

          <div class="table-responsive-md mt-5 table-scrollable" data-controller="table">
            <%= table_tag class: 'table' do %>
              <thead>
                <tr>
                  <%= table_header_tag t('.search.office.title'), class: 'text-left', sorter: 'text' %>
                  <% @data[:years].each do |year| %>
                    <%= table_header_tag year, class: 'text-left', sorter: 'number' %>
                  <% end %>
                </tr>
              </thead>
              <tbody>
                <% @data[:data].select { |e| e[:table] == true }.each do |value| %>
                  <tr>
                    <th class="text-left" scope="row" data-value="<% value[:office] ? value[:office] : 'a' %>">
                      <%= minified_office_name(value[:name]) %>
                    </th>

                    <% value[:data].each do |count| %>
                      <td  data-value="<%= count || -1 %>"><%= count ? trim(number_with_delimiter(count), length: 5) : '&ndash;'.html_safe %></td>
                    <% end %>
                  </tr>
                <% end %>
              </tbody>
            <% end %>
          </div>

          <div class="d-flex flex-wrap align-items-center justify-content-between">
            <div class="small text-muted mr-3 mt-3">
              <%= t 'layouts.search.found_html', count: number_with_delimiter(@search.current.count), total: I18n.t('statistics.count', count: number_with_delimiter(@count)) %>
            </div>

            <div class="small mt-3 text-muted float-right text-right">
              <%= t '.data_source_disclaimer_html' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>