config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :username))
      ) &&
        ActiveSupport::SecurityUtils.secure_compare(
          ::Digest::SHA256.hexdigest(password),
          ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :password))
        )
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :offices, only: %i[index show] do
    get :suggest, on: :collection
    get :decrees, on: :member
  end

  resources :prosecutors, only: %i[index show] do
    get :suggest, on: :collection
    get :export, on: :collection
  end

  resources :statistics, only: :index, path: :'criminality/prosecutors' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  resources :crimes, only: :index, path: :'criminality/police' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  # error pages
  %w[400 404 422 500 503].each { |code| get "/#{code}", to: 'errors#show', code: code }

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/models/crime.rb
# == Schema Information
#
# Table name: crimes
#
#  id         :bigint           not null, primary key
#  count      :integer          not null
#  metric     :string           not null
#  paragraph  :string
#  year       :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_crimes_on_year_and_metric_and_paragraph  (year,metric,paragraph) UNIQUE
#
class Crime < ApplicationRecord
  validates :year, presence: true, numericality: { in: 1997..2020 }
  validates :metric,
            presence: true,
            uniqueness: {
              scope: %i[year paragraph]
            },
            inclusion: {
              in: -> { GROUPS.values.flatten }
            }
  validates :count, presence: true, numericality: true

  def self.import_from(records)
    Crime.transaction do
      Crime.delete_all
      Crime.lock

      Rails.logger.silence do
        records.each do |record|
          Crime.upsert(
            record.slice(:year, :metric, :paragraph, :count),
            unique_by: %i[year metric paragraph],
            returning: false
          )
        end
      end
    end

    nil
  end

  GROUPS = {
    crimes: %i[
      crime_discovered
      crime_solved
      crime_denominated_damage
      crime_additionally_solved
      crime_alcohol_abuse
      crime_drug_abuse
      crime_underage_offender
      crime_underage_offender_alcohol_abuse
      crime_underage_offender_drug_abuse
      crime_adolescent_offender
      crime_adolescent_offender_alcohol_abuse
      crime_adolescent_offender_drug_abuse
    ],
    persons: %i[
      persons_all
      persons_alcohol_abuse
      persons_drug_abuse
      persons_underage_offender
      persons_underage_offender_alcohol_abuse
      persons_underage_offender_drug_abuse
      persons_adolescent_offender
      persons_adolescent_offender_alcohol_abuse
      persons_adolescent_offender_drug_abuse
    ]
  }
end

app/controllers/crimes_controller.rb
class CrimesController < ApplicationController
  def index
    @search = CrimeSearch.new(index_params)
    @time = Benchmark.realtime { @data = @search.data } * 1000
    @count = Rails.cache.fetch('crimes_count', expires_in: 1.day) { Crime.count }
  end

  def suggest
    return head 404 unless suggest_params[:facet].in?(%w[paragraph])

    @search = CrimeSearch.new(suggest_params)

    render(
      json: {
        html:
          render_to_string(
            partial: "#{suggest_params[:facet]}_results",
            locals: {
              values: @search.facets_for(suggest_params[:facet], suggest: suggest_params[:suggest]),
              params: @search.params.merge("#{suggest_params[:facet]}_suggest" => suggest_params[:suggest])
            }
          )
      }
    )
  end

  def png
    path = Rails.root.join('tmp', "crimes-export-#{SecureRandom.hex}.png")
    url = export_crimes_url(index_params)

    options = Selenium::WebDriver::Chrome::Options.new(args: %w[headless])
    options.add_argument('--window-size=1400,760')
    options.add_argument('--enable-font-antialiasing')
    options.add_argument('--force-device-scale-factor=2')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-extensions')
    options.add_argument('--disable-gpu')
    options.add_argument('--disable-setuid-sandbox')
    options.add_option(:detach, false)
    driver = Selenium::WebDriver.for(:chrome, options: options)

    begin
      driver.get(url)
      driver.manage.window.resize_to(1400, driver.execute_script('return document.body.scrollHeight') + 25)
      driver.save_screenshot(path)

      File.open(path, 'rb') do |file|
        send_data(file.read, type: 'image/png', filename: 'otvorena-prokuratura-kriminalita-policia-export.png')
      end
    rescue Exception => e
      raise e
    ensure
      driver.quit
      File.delete(path)
    end
  end

  def export
    response.headers['X-FRAME-OPTIONS'] = 'ALLOWALL'

    index

    render layout: 'export'
  end

  def embed
    index
  end

  private

  helper_method :index_params

  def index_params
    params.permit(:comparison, :paragraph_suggest, :show_default_paragraphs, year: [], metric: [], paragraph: [])
  end

  def suggest_params
    params.permit(:facet, :suggest)
  end
end

app/helpers/crimes_helper.rb
module CrimesHelper
  def crimes_subtitle(search)
    metrics = search.current_statistic_metrics.map(&:to_sym)
    paragraphs = search.current_statistic_paragraphs
    groups = Crime::GROUPS.select { |group, values| (metrics & values).any? }.keys
    key = search.default_params? ? 'crimes.index.subtitle_for_default_params' : 'crimes.index.subtitle'

    translations = groups.map { |group| I18n.t("crimes.index.search.#{group}.title", default: nil) }.compact

    if search.monetary_metric_present?
      search.current_statistic_metrics.size > 1 ?
        translations << I18n.t('crimes.index.monetary_subtitle') :
        translations = [I18n.t('crimes.index.monetary_subtitle')]
    end

    paragraphs -= %w[_all] if paragraphs

    return translations.to_sentence.html_safe if paragraphs&.compact.blank?

    paragraph_names = paragraphs.map { |value| Paragraph.by_value[value] }

    paragraphs_list =
      content_tag :div, class: 'mt-3' do
        content_tag :small do
          content_tag :ul, class: 'list-unstyled ml-3 paragraphs-list' do
            paragraph_names
              .map do |name|
                content_tag(:li, class: 'mt-1 d-flex') do
                  (
                    content_tag(:span, name, class: 'text-truncate') +
                      (
                        if Paragraph.type_of(Paragraph.by_name[name]) == :old
                          content_tag(:span, class: 'ml-2 facet-tag') do
                            tooltip_tag(
                              I18n.t('statistics.index.search.paragraph.old.badge'),
                              I18n.t('statistics.index.search.paragraph.old.title')
                            )
                          end
                        else
                          ''
                        end
                      ) +
                      link_to(
                        '&times;'.html_safe,
                        crimes_path(
                          search_params(
                            @search.params.merge(paragraph: paragraphs),
                            { paragraph: Paragraph.by_name[name] }
                          )
                        ),
                        class: 'flex-fill ml-2 cancel'
                      )
                  ).html_safe
                end
              end
              .join
              .html_safe
          end
        end
      end

    [
      translations.to_sentence,
      I18n.t('crimes.index.by_paragraphs_subtitle', paragraphs: paragraphs_list).html_safe
    ].join(' ').html_safe
  end
end

app/views/crimes/_paragraph_results.html.erb
<ul class="facet-list facet-list-scrollable mb-2" data-target="suggest.results">
  <% if values.any? %>
    <% values.each do |value, _| %>
      <li class="facet-item">
        <%= link_to crimes_path(search_params(params, { paragraph: value })), class: "facet-link#{' active' if search_param?(params, :paragraph, value)}" do %>
          <%= trim(Paragraph.name_of(value), length: 24) %>

          <div class="facet-tag">
            <% if (type = Paragraph.type_of(value)) == :old %>
              <%= tooltip_tag(I18n.t("statistics.index.search.paragraph.old.badge"),  I18n.t("statistics.index.search.paragraph.old.title"), class: 'd-inline') %>
            <% end %>
          </div>
        <% end %>
      </li>
    <% end %>
  <% else %>
    <li class="facet-item">
      <span class="text-muted"><%= t 'statistics.index.search.paragraph.not_found' %></span>
    </li>
  <% end %>
</ul>

app/views/crimes/embed.html.erb
<iframe src="<%= export_crimes_url(@search.params.merge(embedded: true)) %>" width="100%" height="<%= params[:show_default_paragraphs].present? ? 1280 : 800 %>px" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups">
  <p>
    <a href="https://developer.mozilla.org/en-US/docs/Glossary">Fallback link for browsers that don't support iframes</a>
  </p>
</iframe>

<div class="form-group">
  <textarea name="embed" id="embed" rows="10" cols="40" class="w-100 mt-3 form-control" disabled="true">
    <iframe src="<%= export_crimes_url(@search.params.merge(embedded: true)) %>" width="100%" height="<%= params[:show_default_paragraphs].present? ? 1280 : 800 %>px" frameborder="0" sandbox="allow-same-origin allow-scripts allow-popups">
      <p>
        <a href="https://developer.mozilla.org/en-US/docs/Glossary">Fallback link for browsers that don't support iframes</a>
      </p>
    </iframe>
  </textarea>
</div>

app/views/crimes/export.html.erb
<div class="statistics-export">
  <div class="d-flex flex-wrap align-items-center justify-content-between">
  <h1 class="display-2 text-uppercase mr-sm-4 mt-1 pr-5">
    <%= t 'crimes.index.title' %>
  </h1>

  <%= brand_tag('transparency-international-slovensko', width: 197.92, height: 47.5, variant: I18n.locale) %>

  <div
    class="w-100"
    data-controller="crimes-chart"
    data-json="<%= @data.to_json %>"
    data-comparison="<%= @search.comparison %>"
    data-animation="false"
  >
    <h1 class="text-uppercase">
      <small class="text-muted">
        <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
          <%= t 'crimes.index.subtitle_for_default_params' %>
        <% else %>
          <%= crimes_subtitle(@search) %>
        <% end %>
      </small>
    </h1>

    <% if @search.data[:data].present? %>
      <div class="mt-5 chart"></div>

      <small class="mt-2 text-muted float-right text-right">
        <%= t 'statistics.index.data_disclaimer' %>
        <br>
        <% if params[:embedded] %>
          <%= link_to t('.open_in_application'), statistics_url(@search.params), class: 'text-muted', target: :_blank %>
          &middot;&nbsp;
        <% end %>
        <%= t 'statistics.index.data_source_disclaimer_html' %>
      </small>
    <% else %>
      <p class="text-center text-muted mt-5 p-5"><%= t '.no_data' %></p>
    <% end %>
  </div>
</div>

app/views/crimes/index.html.erb
<% provide :title, t('.page_title') %>

<%
  @time = Benchmark.realtime do
    @data = @search.data
  end * 1000
%>

<div class="container px-sm-0" data-controller="facets">
  <div class="clearfix">
    <div id="facets" class="float-lg-left col-lg-3 mb-5 mb-lg-0 px-0 pr-lg-4 collapse show">
      <div class="facet" data-controller="suggest" data-url="<%= suggest_crimes_path(@search.params.merge(facet: :paragraph)) %>">
        <h6 class="facet-title" data-toggle="collapse" data-target="#crimes-paragraph-content">
          <%= t "statistics.index.search.paragraph.title" %>
        </h6>

        <div id="crimes-paragraph-content" class="facet-content collapse show">
          <div class="facet-results">
            <input value="<%= params[:paragraph_suggest] %>" class="facet-suggest ui-autocomplete-input" name="paragraph" data-target="suggest.query" data-action="keyup->suggest#onChange" placeholder="<%= t 'statistics.index.search.paragraph.placeholder' %>" type="text" autocomplete="off">

            <% if (facets = @search.facets_for(:paragraph, selected_first: true)).any? %>
              <ul class="facet-list">
                <li class="facet-item">
                  <%= link_to crimes_path(search_params(@search.params, { paragraph: '_all', paragraph_suggest: nil, }, replace: true)), class: "facet-link#{' active' if @search.params[:paragraph].blank? && !@search.default_params?}" do %>
                    <%= t('statistics.index.search.paragraphs.all') %>
                  <% end %>
                </li>
              </ul>
            <% end %>

            <%= render "paragraph_results", values: facets, params: @search.params %>

            <small class="text-muted mt-2"><%= t 'statistics.index.search.paragraph.disclaimer' %></small>
          </div>
        </div>
      </div>

      <div class="facet">
        <h6 class="facet-title" data-toggle="collapse" data-target="#crimes-year-content">
          <%= t 'statistics.index.search.year.title' %>
        </h6>

        <div id="crimes-year-content" class="facet-content collapse show">
          <div class="facet-results">
            <ul class="facet-list">
              <li class="facet-item">
                <%= link_to crimes_path(search_params(@search.params, { year: nil })), class: "facet-link#{' active' if @search.params[:year].blank?}" do %>
                  <%= t('statistics.index.search.year.all') %>
                <% end %>
              </li>
            </ul>

            <% if @search.facets_for(:year).tap do |facets| %>
              <%= collapsible_facet_results(facets, selected: @search.params[:year]) do |key, _| %>
                <li class="facet-item">
                  <%= link_to crimes_path(search_params(@search.params, { year: key })), class: "facet-link#{' active' if search_param?(@search.params, :year, key)}" do %>
                    <%= key %>
                  <% end %>
                </li>
              <% end %>
            <% end.empty? %>
              <span class="text-muted"><%= t 'statistics.index.search.year.not_found' %></span>
            <% end %>
          </div>
        </div>
      </div>

      <% Crime::GROUPS.each do |group, metrics| %>
        <% metrics.select { |metric| @search.has_metric?(metric) }.tap do |facets| %>
          <% if facets.any? %>
            <div class="facet">
              <h6 class="facet-title" data-toggle="collapse" data-target="#crimes-<%= group %>-content">
                <%= t ".search.#{group}.title" %>
              </h6>

              <div id="crimes-<%= group %>-content" class="facet-content collapse show">
                <div class="facet-results">
                  <%= collapsible_facet_results(facets, selected: @search.params[:metric]) do |key| %>
                    <li class="facet-item">
                      <%= link_to crimes_path(search_params(@search.params, { metric: key })), class: "facet-link#{' active' if search_param?(@search.params, :metric, key)}" do %>
                        <%= trim(t("models.crime.metrics.#{key}"), length: 30) %>
                      <% end %>
                    </li>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="float-lg-right col-lg-9 px-0" data-results-for-facets>
      <div class="d-flex flex-wrap align-items-center justify-content-between">
        <h1 class="display-2 text-uppercase mr-sm-4 mt-1 pr-5">
          <%= t '.title' %>
        </h1>

        <div class="btn-toolbar" role="toolbar">
          <% if @search.params.any? { |_, v| v.present? } %>
            <div class="btn-group btn-group-sm border mb-3 mr-2" role="group">
              <%= link_to t('layouts.search.reset'), crimes_path, class: 'btn btn-secondary btn-sm shadow-none border-0 w-100', 'data-turbo': false %>
            </div>
          <% end %>

          <div class="btn-group btn-group-sm border mb-3" role="group">
            <a href="#" class="btn btn-secondary btn-sm shadow-none border-0 w-100" data-toggle="collapse" data-target="#facets" aria-controls="#facets" aria-expanded="true">
              <span class="show"><%= t 'statistics.index.shrink_chart' %></span>
              <span class="hide"><%= t 'statistics.index.enlarge_chart' %></span>
            </a>
          </div>

          <div class="btn-group btn-group-sm border mb-3 ml-2">
            <div class="btn-group btn-group-sm flex-grow-1 d-flex" role="group">
              <button type="button" class="btn btn-secondary dropdown-toggle shadow-none border-0 flex-grow-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= t 'Export' %>
              </button>
              <div class="dropdown-menu dropdown-menu-sm">
                <%= link_to 'PNG', png_crimes_path(index_params), class: 'dropdown-item', target: :_blank %>
                <%= link_to 'Embed', embed_crimes_path(index_params), class: 'dropdown-item', target: :_blank %>
              </div>
            </div>
          </div>
        </div>

        <div
          class="w-100"
          data-controller="crimes-chart"
          data-watermark-url="<%= image_url("brands/transparency-international-slovensko.#{I18n.locale}.svg") %>"
          data-comparison="<%= @search.comparison %>"
          data-json="<%= @data.to_json %>"
        >
          <h1 class="text-uppercase">
            <small class="text-muted">
              <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
                <%= t '.subtitle_for_default_params' %>
              <% else %>
                <%= crimes_subtitle(@search) %>
              <% end %>
            </small>
          </h1>

          <% if @search.default_params? && params[:show_default_paragraphs].blank? %>
            <%= link_to t('.show_paragraphs'), crimes_path(@search.params.merge(show_default_paragraphs: true)), class: 'text-muted' %>
          <% end %>

          <% if @data[:data].any? %>
            <div class="mt-5 chart"></div>

            <small class="mt-2 text-muted float-right text-right">
              <%= t '.data_disclaimer' %>
            </small>
          <% else %>
            <p class="text-center text-muted mt-5 p-5"><%= t '.no_data' %></p>
          <% end %>

          <% @data[:data].group_by { |e| e[:group] }.each.with_index do |(group, values), i| %>
            <div class="table-responsive-md table-scrollable <%= i == 0 ? 'mt-5' : 'mt-1' %>" data-controller="table">
              <%= table_tag class: 'table' do %>
                <thead>
                  <tr>
                    <%= table_header_tag t(".search.#{group}.title"), class: 'text-left text-nowrap', sorter: 'text' %>
                    <% @data[:years].each do |year| %>
                      <%= table_header_tag year, class: 'text-left', sorter: 'number' %>
                    <% end %>
                  </tr>
                </thead>
                <tbody>
                  <% values.reject { |e| e[:monetary] }.each do |value| %>
                    <tr>
                      <th class="text-left text-nowrap" scope="row" data-value="<%= value[:name] %>">
                        <%= t("models.crime.metrics.#{value[:metric]}") %>
                      </th>

                      <% value[:data].each do |count| %>
                        <td class="text-nowrap text-left" data-value="<%= count || -1 %>"><%= count ? trim(number_with_delimiter(count), length: 7) : '&ndash;'.html_safe %></td>
                      <% end %>
                    </tr>
                  <% end %>
                </tbody>

                
                <tfoot>
                  <% values.select { |e| e[:monetary] }.each do |value| %>
                    <tr class="table-secondary text-nowrap">
                      <th class="text-left" scope="row" data-value="<%= value[:name] %>">
                        <%= t("models.crime.metrics.#{value[:metric]}") %>
                      </th>

                      <% value[:data].each do |count| %>
                        <td>
                          <span data-toggle="tooltip" title="<%= number_to_currency(number_with_delimiter(count), unit: '€') %>">
                          <%= count ? number_to_currency(number_to_abbreviation(count), unit: '€') : '&ndash;'.html_safe %>
                        </td>
                      <% end %>
                    </tr>
                  <% end %>
                </tfoot>
              <% end %>
            </div>
          <% end %>

          <div class="d-flex flex-wrap align-items-center justify-content-between">
            <div class="small text-muted mr-3 mt-3">
              <%= t 'layouts.search.found_html', count: number_with_delimiter(@search.current.count), total: I18n.t('statistics.count', count: number_with_delimiter(@count)) %>
            </div>

            <div class="small mt-3 text-muted float-right text-right">
              <%= t '.data_source_disclaimer_html' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>