config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'static_pages#home'

  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      ActiveSupport::SecurityUtils.secure_compare(
        ::Digest::SHA256.hexdigest(username),
        ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :username))
      ) &&
        ActiveSupport::SecurityUtils.secure_compare(
          ::Digest::SHA256.hexdigest(password),
          ::Digest::SHA256.hexdigest(Rails.application.credentials.dig(:sidekiq, :password))
        )
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  resources :offices, only: %i[index show] do
    get :suggest, on: :collection
    get :decrees, on: :member
  end

  resources :prosecutors, only: %i[index show] do
    get :suggest, on: :collection
    get :export, on: :collection
  end

  resources :statistics, only: :index, path: :'criminality/prosecutors' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  resources :crimes, only: :index, path: :'criminality/police' do
    get :suggest, on: :collection
    get :png, on: :collection
    get :export, on: :collection
    get :embed, on: :collection
  end

  # error pages
  %w[400 404 422 500 503].each { |code| get "/#{code}", to: 'errors#show', code: code }

  match '/:slug', via: :get, to: 'static_pages#show', as: :static_page
end

app/views/layouts/_footer.html.erb
<footer class="container small mt-5 px-sm-0 py-3">
  <div class="d-flex align-items-start align-items-xl-center text-uppercase border-bottom mb-3">
    <nav class="nav nav-primary flex-row flex-grow-1 mb-3">
      <div class="d-flex flex-column flex-xl-row flex-grow-1 flex-xl-grow-0 mr-4 mr-xl-0">
        <%= link_to t('.about'), static_page_path('about'), class: 'nav-link ml-0 mr-auto mr-xl-3' %>
        <%= link_to t('.analyses'), 'https://transparency.blog.sme.sk/', class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3', target: :_blank %>
        <%= link_to t('.faq'), static_page_path('faq'), class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3' %>
        <%= link_to t('.feedback'), static_page_path('feedback'), class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3' %>
      </div>
      <div class="d-flex flex-column flex-xl-row flex-grow-1 flex-xl-grow-0 mr-4">
        <%= link_to t('.tos'), static_page_path('tos'), class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3' %>
        <%= link_to t('.privacy'), static_page_path('privacy'), class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3' %>
        <%= link_to t('.api'), 'https://api.otvorenesudy.sk', class: 'nav-link ml-0 ml-xl-3 mr-auto mr-xl-3', target: :_blank %>
        <%= link_to t('.contact'), static_page_path('contact'), class: 'nav-link ml-0 ml-xl-3 mr-0' %>
      </div>
    </nav>

    <nav class="nav nav-primary flex-column flex-md-row flex-nowrap align-items-center justify-content-center mb-3">
      <%= link_to t('.donate'), donation_url, class: 'btn btn-primary order-first order-md-last', role: :button, target: :_blank %>
    </nav>
  </div>

  <div class="d-flex flex-wrap align-items-center justify-content-between mb-3">
    <nav class="nav justify-content-start col mr-3 mb-3 p-0">
      <%= link_to brand_tag('transparency-international-slovensko', width: 158.33, height: 38, variant: I18n.locale), 'https://transparency.sk', class: 'tis' %>
    </nav>

    <div class="flex-grow-1 flex-grow-lg-0 text-center order-last order-lg-0 border-top border-top-lg-0 mb-3">
      <nav class="nav nav-secondary justify-content-center mt-3 mt-lg-0 mb-2 mb-md-0">
        <%= link_to 'Transparency International Slovensko', 'https://transparency.sk', class: 'nav-link font-weight-bold mb-2 mb-sm-0' %>
        <%= link_to "&copy; #{Date.current.year}".html_safe, static_page_path('copyright'), class: 'nav-link' %>
        <%= link_to 'otvorenesudy', organisation_url, class: 'nav-link' %>
        <%= link_to OpenCourts::Prokuratura::VERSION::STRING, repository_url("releases/tag/v#{OpenCourts::Prokuratura::VERSION::STRING}"), class: 'nav-link' %>
      </nav>
      <%= t '.disclaimer.resources' %>
      <br class="d-inline d-md-none" />
      <%= t '.disclaimer.correctness' %>
    </div>

    <nav class="nav flex-nowrap justify-content-end col ml-3 mb-3 p-0">
      <%= link_to icon_tag('facebook', size: 24), 'https://facebook.com/transparencysk', class: 'nav-link m-0' %>
      <%= link_to icon_tag('twitter', size: 24), 'https://twitter.com/transparencysk', class: 'nav-link mx-1 m-0' %>
      <%= link_to icon_tag('youtube', size: 24), 'https://www.youtube.com/user/TISlovensko', class: 'nav-link m-0' %>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="container mt-3 px-sm-0">
  <nav class="nav flex-column flex-md-row align-items-between align-items-md-center">
    <div class="nav flex-grow-1 justify-content-between mr-md-4 mb-3">
      <%= link_to brand_tag('otvorena-prokuratura', { height: 60 , width: 225 }), root_path, class: 'navbar-brand mr-3 mr-md-4' %>

      <div class="nav nav-secondary justify-content-center align-items-center align-self-stretch font-weight-bold text-uppercase small border-right-md pr-md-4">
        <%= link_to span_tag(t('.slovak'), class: 'd-none d-lg-inline') + span_tag(t('.sk'), class: 'd-lg-none'), { l: :sk }, class: 'nav-link' %>
        <%= link_to span_tag(t('.english'), class: 'd-none d-lg-inline') + span_tag(t('.en'), class: 'd-lg-none'), { l: :en }, class: 'nav-link' %>
      </div>
    </div>

    <div class="nav flex-grow-1 flex-md-grow-0 flex-wrap justify-content-between align-items-center border-top border-top-md-0 mb-3">
      <%= link_to brand_tag('transparency-international-slovensko', width: 158.33, height: 38, variant: I18n.locale), 'https://transparency.sk', class: 'tis d-block mr-3 mr-md-4 mt-3 mt-md-0' %>
      <%= link_to t('.donate'), donation_url, class: 'btn btn-primary btn-lg mt-3 mt-md-0', role: :button, target: :_blank %>
    </div>
  </nav>

  <nav class="navbar nav-primary navbar-expand-xl font-weight-bold text-uppercase border-bottom">
    <div class="d-flex d-xl-none justify-content-between border-top w-100 py-2">
      <%= button_tag t('.menu'), class: 'navbar-toggler mx-0', data: { toggle: 'collapse', target: '#navbar' }, name: nil, type: 'button' %>
      <%= button_tag '&#9776;'.html_safe, class: 'navbar-toggler', data: { toggle: 'collapse', target: '#navbar' }, name: nil, type: 'button' %>
    </div>

    <div id="navbar" class="navbar-collapse collapse d-xl-block border-top">
      <div class="navbar-nav justify-content-between py-2">
        <%= bar_link_to t('.prosecutors'), prosecutors_path, class: 'mx-0' %>
        <%= bar_link_to t('.offices'), offices_path, class: 'mx-0' %>
        <%= dropdown_bar_link_to t('.criminality.title'), '/criminality', [{ title: t('.criminality.prosecutors'), path: statistics_path}, { title: t('.criminality.police'), path: crimes_path}], class: 'mx-0' %>   
        <%= bar_link_to t('.otvorenesudy'), 'https://otvorenesudy.sk', class: 'mx-0', target: :_blank %>
      </li>
      </li>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<html lang="<%= I18n.locale %>">
  <head>
    <script async data-category="analytics" data-service="Google Analytics" src="https://www.googletagmanager.com/gtag/js?id=<%= Rails.application.credentials.dig(:google, :analytics, :tracking_id) %>"></script>
    <script data-category="analytics" data-service="Google Analytics">
      window.dataLayer = window.dataLayer || [];

      function gtag() { dataLayer.push(arguments); }

      gtag('js', new Date());
      gtag('config', '<%= Rails.application.credentials.dig(:google, :analytics, :tracking_id) %>');

      document.addEventListener('turbo:load', event => {
        if (typeof gtag === 'function') {
          gtag('config', '<%= Rails.application.credentials.dig(:google, :analytics, :tracking_id) %>', {
            'page_location': event.detail.url
          });
        }
      });
    </script>

    <meta charset="utf-8" />
    <title><%= resolve_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="<%= t '.description'%>" />
    <meta name="keywords" content="<%= t '.keywords' %>" />
    <meta name="author" content="<%= t '.authors' %>" />
    <meta property="og:title" content="<%= resolve_title(yield :title) %>" />
    <meta property="og:description" content="<%= t '.content' %>" />
    <meta property="og:image" content="<%= asset_path "brands/otvorena-prokuratura.svg" %>" />
    <meta property="og:url" content="<%= canonical_url %>" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:title" content="<%= resolve_title(yield :title) %>" />
    <meta name="twitter:description" content="<%= t '.content' %>" />
    <meta name="twitter:image" content="<%= asset_path "brands/otvorena-prokuratura.svg" %>" />
    <meta name="twitter:url" content="<%= canonical_url %>" />
    <link rel="mask-icon" href="<%= asset_path 'maskicon.svg' %>" sizes="any" />
    <link rel="apple-touch-icon" href="<%= asset_path 'touchicon.png' %>" />
    <link rel="icon" href="<%= asset_path 'favicon.png' %>" />
    <meta name="msapplication-TileImage" content="<%= asset_path 'tileicon.png' %>" />
    <meta name="msapplication-TileColor" content="#fff" />
    <link rel="prefetch" href="<%= asset_path 'icons.svg' %>" />
    <link rel="prefetch" href="<%= asset_path 'brands.svg' %>" />
    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Ubuntu:300,700&subset=latin-ext" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.0.1/dist/cookieconsent.umd.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container mt-4 px-sm-0">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/export.html.erb
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8" />
    <title><%= resolve_title(yield :title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="prefetch" href="<%= asset_path 'icons.svg' %>" />
    <link rel="prefetch" href="<%= asset_path 'brands.svg' %>" />
    <link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Ubuntu:300,700&subset=latin-ext" />
    <link type="text/css" rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin=""/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>
  <body>
    <div class="container mt-4 px-sm-0">
      <%= yield %>
    </div>
  </body>
</html>